/* ==========================================================================
   Global Paints & Coatings — Data Model
   Source of truth: product-specification PDF (technical data) and the
   company profile PDF (aliases, story, awards). Do not add figures here
   that are not backed by those documents.
   ========================================================================== */

let COMPANY = {
  name: "Global Paints & Coatings",
  tagline: "Let Us Color Your World.",
  founder: "Milton Manda",
  address: "36 Mpumelelo Road, Kelvin North, Bulawayo, Zimbabwe",
  email: "globalpaintzim@gmail.com",
  phone: "078 028 1611",
  phoneAlt: "+263 77 980 0917",
  whatsappNumber: "263712397200",
  radio: "Skyz Metro FM 100.3",
};

function waLink(message) {
  const base = `https://wa.me/${COMPANY.whatsappNumber}`;
  return message ? `${base}?text=${encodeURIComponent(message)}` : base;
}

let AWARDS = [
  { year: "2023", title: "SME Graduation Certificate", detail: "Graduated from Micro to Small Enterprise — 9 June 2023." },
  { year: "2024", title: "Bronze Winner, Male Entrepreneur of the Year", detail: "Megafest Business Awards, Southern Region — 6 December 2024." },
  { year: "2025", title: "Certificate of Appreciation", detail: "The Neighbour Magazine SME Business Awards — December 2025." },
  { year: "2026", title: "Certificate of Excellence, Best Paints & Coatings Supplier", detail: "Bulawayo Business Awards — 2026." },
];

/* Surface/use filter taxonomy used across products.html and the calculator */
const SURFACES = [
  { id: "interior", label: "Interior walls" },
  { id: "exterior", label: "Exterior walls" },
  { id: "roofs", label: "Roofs, concrete & stoeps" },
  { id: "wood", label: "Wood" },
  { id: "metal", label: "Metal" },
  { id: "masonry", label: "Masonry" },
  { id: "waterproofing", label: "Waterproofing" },
  { id: "preparation", label: "Preparation" },
];

/* Each product's `image` is only set where a real supplied photo exists.
   Everything else renders a restrained data card instead of a fabricated
   bucket image. `coverageLow` / `coverageHigh` power the calculator. */
let PRODUCTS = [
  {
    slug: "wall-coat",
    name: "Wall Coat",
    alias: null,
    tagline: "Durable acrylic/PVA coating for interior & exterior masonry.",
    description: "Acrylic/PVA wall coating designed for durable decorative protection of interior and exterior masonry surfaces. Suitable for properly prepared surfaces, with good adhesion and coverage.",
    use: "Interior/exterior walls",
    size: "20L",
    coverageLow: 100, coverageHigh: 120,
    lifespan: "5–7 years",
    surfaces: ["interior", "exterior"],
    colours: ["Grey", "Cream", "White"],
    features: ["Smooth, durable finish", "Good adhesion", "Easy application", "Suitable for properly prepared masonry surfaces", "Good coverage", "Recommended: 2 coats for a uniform finish"],
    recommendedCoats: 2,
    availableSizes: [20],
    image: "assets/products/wall-coat.jpg",
    price: 25,
  },
  {
    slug: "wall-primer",
    name: "Wall Primer",
    alias: "also on packaging as Gorilla Primer",
    tagline: "Penetrating primer that prepares porous walls before finishing.",
    description: "Penetrating/sealing primer that prepares porous surfaces and improves the adhesion and uniformity of the finishing coat.",
    use: "Sealing and preparing walls",
    size: "20L",
    coverageLow: 100, coverageHigh: 120,
    lifespan: "5+ years as primer",
    surfaces: ["preparation", "interior", "exterior"],
    colours: null,
    recommendedCoats: 1,
    availableSizes: [20],
    image: "assets/products/wall-primer.jpg",
    price: 17,
  },
  {
    slug: "roof-and-stoep",
    name: "Roof & Stoep",
    alias: "also on packaging as Giraffe Roof & Stoep",
    tagline: "Protective coating for roofs, floors, concrete and stoeps.",
    description: "Durable coating for concrete, masonry and suitable roof/floor surfaces, providing colour and protective coverage.",
    use: "Roofs, floors, concrete & stoeps",
    size: "5L",
    coverageLow: 25, coverageHigh: 35,
    lifespan: "3–5 years",
    surfaces: ["roofs"],
    colours: null,
    recommendedCoats: 2,
    availableSizes: [5],
    image: null,
    price: 15,
  },
  {
    slug: "elegant-silk-interior",
    name: "Elegant Silk Interior",
    alias: "also on packaging as Lion Silk Washable / Elegant Silk",
    tagline: "Premium washable interior finish with a smooth silk sheen.",
    description: "Premium washable interior coating with a smooth silk appearance, designed for areas requiring an attractive and cleanable finish.",
    use: "Premium interior walls",
    size: "20L",
    coverageLow: 100, coverageHigh: 120,
    lifespan: "7–8 years",
    surfaces: ["interior"],
    colours: null,
    features: ["Smooth silk finish", "Excellent washability", "Excellent hiding", "Low odour", "Durable", "Resists yellowing", "Luxurious & elegant finish", "Excellent coverage", "Quick dry"],
    recommendedCoats: 2,
    availableSizes: [20],
    image: "assets/products/elegant-silk.jpg",
    price: 65,
  },
  {
    slug: "weather-coat-exterior",
    name: "Weather Coat Exterior",
    alias: "also on packaging as Elephant Exterior",
    tagline: "Exterior-grade colour and protection against outdoor weathering.",
    description: "Exterior-grade coating formulated to provide decorative colour and protection against normal outdoor weathering.",
    use: "Exterior walls",
    size: "20L",
    coverageLow: 90, coverageHigh: 110,
    lifespan: "5–7 years",
    surfaces: ["exterior"],
    colours: null,
    recommendedCoats: 2,
    availableSizes: [20],
    image: null,
    price: 65,
  },
  {
    slug: "universal-undercoat",
    name: "Universal Undercoat",
    alias: null,
    tagline: "High-build preparatory coat for wood and metal.",
    description: "High-build preparatory coating designed to improve adhesion, coverage and finish consistency before the final coat.",
    use: "Wood and metal preparation",
    size: "20L",
    coverageLow: 100, coverageHigh: 120,
    lifespan: "5+ years as undercoat",
    surfaces: ["preparation", "wood", "metal"],
    colours: null,
    recommendedCoats: 1,
    availableSizes: [20],
    image: null,
    price: 80,
  },
  {
    slug: "pinkwood-primer",
    name: "Pinkwood Primer",
    alias: "also on packaging as Pink Wood Primer",
    tagline: "Wood primer that seals and prepares timber for finishing.",
    description: "Wood primer designed to seal and prepare timber before application of the finishing coat.",
    use: "Wooden surfaces",
    size: "5L",
    coverageLow: 25, coverageHigh: 35,
    lifespan: "5+ years as primer",
    surfaces: ["preparation", "wood"],
    colours: null,
    recommendedCoats: 1,
    availableSizes: [5],
    image: null,
    price: 20,
  },
  {
    slug: "red-oxide",
    name: "Red Oxide",
    alias: null,
    tagline: "Anti-corrosive primer for ferrous metal.",
    description: "Anti-corrosive primer for ferrous metal surfaces before application of a suitable finishing coat.",
    use: "Ferrous metal protection",
    size: "5L",
    coverageLow: 25, coverageHigh: 35,
    lifespan: "3–5 years",
    surfaces: ["metal", "preparation"],
    colours: null,
    recommendedCoats: 1,
    availableSizes: [5],
    image: null,
    price: 15,
  },
  {
    slug: "gloss-enamel",
    name: "Gloss Enamel",
    alias: null,
    tagline: "High-gloss finish for properly prepared wood and metal.",
    description: "High-gloss decorative finish for properly prepared wood and metal surfaces.",
    use: "Wood and metal finishing",
    size: "5L",
    coverageLow: 30, coverageHigh: 40,
    lifespan: "5–7 years",
    surfaces: ["wood", "metal"],
    colours: null,
    recommendedCoats: 2,
    availableSizes: [5],
    image: null,
    price: 25,
  },
  {
    slug: "brick-dressing",
    name: "Brick Dressing",
    alias: null,
    tagline: "Protective, decorative coating for brick and masonry.",
    description: "Protective decorative coating for brick and masonry, enhancing appearance while helping protect the substrate.",
    use: "Brick and masonry surfaces",
    size: "5L",
    coverageLow: 25, coverageHigh: 40,
    lifespan: "3–5 years",
    surfaces: ["masonry"],
    colours: null,
    recommendedCoats: 2,
    availableSizes: [5],
    image: null,
    price: 25,
  },
  {
    slug: "vanish",
    name: "Vanish",
    alias: null,
    tagline: "Protective finishing and sealing for prepared surfaces.",
    description: "Protective finishing/sealing product for suitable prepared surfaces.",
    use: "Protective finishing/sealing",
    size: "5L",
    coverageLow: 25, coverageHigh: 35,
    lifespan: "3–5 years",
    surfaces: ["preparation"],
    colours: null,
    recommendedCoats: 1,
    availableSizes: [5],
    image: null,
    price: 20,
  },
  {
    slug: "liquid-rubber-paint",
    name: "Liquid Rubber Paint",
    alias: null,
    tagline: "Flexible waterproofing membrane for protection.",
    description: "Flexible waterproofing coating designed to form a protective membrane over suitable surfaces.",
    use: "Waterproofing and protection",
    size: "20L",
    coverageLow: 40, coverageHigh: 60,
    lifespan: "5–10 years",
    surfaces: ["waterproofing"],
    colours: null,
    recommendedCoats: 2,
    availableSizes: [20],
    image: null,
    price: 80,
  },
];

/* Colour Studio — illustrative "colour directions" only. These are NOT
   official Global Paints shade names or paint codes; the exact tint
   catalogue was not supplied. Wall Coat's 3 verified colours (Grey, Cream,
   White) are shown separately on that product's detail page. */
const COLOUR_FAMILIES = [
  {
    id: "whites-creams", name: "Whites & Creams",
    swatches: [
      { name: "Pure White", hex: "#FFFFFF", image: "assets/colours/whites-creams--pure-white.png" },
      { name: "Soft Ivory", hex: "#FAF6EE", image: "assets/colours/whites-creams--soft-ivory.png" },
      { name: "Warm Parchment", hex: "#F3EEDD", image: "assets/colours/whites-creams--warm-parchment.png" },
      { name: "Sandstone Cream", hex: "#EFE7D0", image: "assets/colours/whites-creams--sandstone-cream.png" },
      { name: "Antique Cream", hex: "#E8DEC0", image: "assets/colours/whites-creams--antique-cream.png" },
      { name: "Buttermilk", hex: "#F1E6C8", image: "assets/colours/whites-creams--buttermilk.png" },
      { name: "Chalk White", hex: "#F6F4EF", image: "assets/colours/whites-creams--chalk-white.png" },
      { name: "Linen", hex: "#EDE6D8", image: "assets/colours/whites-creams--linen.png" },
    ],
  },
  {
    id: "neutrals-beiges", name: "Neutrals & Beiges",
    swatches: [
      { name: "Soft Putty", hex: "#E9E2D6", image: "assets/colours/neutrals-beiges--soft-putty.png" },
      { name: "Desert Sand", hex: "#DCD0BE", image: "assets/colours/neutrals-beiges--desert-sand.png" },
      { name: "Warm Taupe", hex: "#C9B99E", image: "assets/colours/neutrals-beiges--warm-taupe.png" },
      { name: "Camel", hex: "#B9A488", image: "assets/colours/neutrals-beiges--camel.png" },
      { name: "Mocha Beige", hex: "#A88F6E", image: "assets/colours/neutrals-beiges--mocha-beige.png" },
      { name: "Stone Grey-Beige", hex: "#CBC0AE", image: "assets/colours/neutrals-beiges--stone-grey-beige.png" },
      { name: "Toasted Almond", hex: "#B99F82", image: "assets/colours/neutrals-beiges--toasted-almond.png" },
      { name: "Driftwood", hex: "#9C8567", image: "assets/colours/neutrals-beiges--driftwood.png" },
    ],
  },
  {
    id: "greys", name: "Greys",
    swatches: [
      { name: "Cloud", hex: "#F1F2F3", image: "assets/colours/greys--cloud.png" },
      { name: "Mist Grey", hex: "#D8DADD", image: "assets/colours/greys--mist-grey.png" },
      { name: "Pebble", hex: "#B7BBC0", image: "assets/colours/greys--pebble.png" },
      { name: "Slate", hex: "#8B9096", image: "assets/colours/greys--slate.png" },
      { name: "Graphite", hex: "#5B6066", image: "assets/colours/greys--graphite.png" },
      { name: "Charcoal", hex: "#3B3F45", image: "assets/colours/greys--charcoal.png" },
      { name: "Dove Grey", hex: "#C4C7CB", image: "assets/colours/greys--dove-grey.png" },
      { name: "Storm", hex: "#6E7480", image: "assets/colours/greys--storm.png" },
    ],
  },
  {
    id: "blues", name: "Blues",
    swatches: [
      { name: "Mist Blue", hex: "#EAF4F8", image: "assets/colours/blues--mist-blue.png" },
      { name: "Sky Wash", hex: "#BFE0EC", image: "assets/colours/blues--sky-wash.png" },
      { name: "Harbour Blue", hex: "#7FB8D6", image: "assets/colours/blues--harbour-blue.png" },
      { name: "Global Blue", hex: "#3E82B0", image: "assets/colours/blues--global-blue.png" },
      { name: "Deep Marine", hex: "#164A78", image: "assets/colours/blues--deep-marine.png" },
      { name: "Denim", hex: "#3D5F82", image: "assets/colours/blues--denim.png" },
      { name: "Teal Wash", hex: "#7EC1C7", image: "assets/colours/blues--teal-wash.png" },
      { name: "Deep Teal", hex: "#0F5560", image: "assets/colours/blues--deep-teal.png" },
    ],
  },
  {
    id: "greens", name: "Greens",
    swatches: [
      { name: "Sage Mist", hex: "#EEF3E7", image: "assets/colours/greens--sage-mist.png" },
      { name: "Soft Fern", hex: "#C9DBB1", image: "assets/colours/greens--soft-fern.png" },
      { name: "Meadow", hex: "#9FC17C", image: "assets/colours/greens--meadow.png" },
      { name: "Leaf Green", hex: "#6B9E4A", image: "assets/colours/greens--leaf-green.png" },
      { name: "Forest", hex: "#43682E", image: "assets/colours/greens--forest.png" },
      { name: "Olive", hex: "#767A3E", image: "assets/colours/greens--olive.png" },
      { name: "Eucalyptus", hex: "#8FAE8C", image: "assets/colours/greens--eucalyptus.png" },
      { name: "Deep Pine", hex: "#2C4A2C", image: "assets/colours/greens--deep-pine.png" },
    ],
  },
  {
    id: "earth-tones", name: "Earth Tones",
    swatches: [
      { name: "Sunbaked Clay", hex: "#EDE0D0", image: "assets/colours/earth-tones--sunbaked-clay.png" },
      { name: "Terracotta Sand", hex: "#D8B98E", image: "assets/colours/earth-tones--terracotta-sand.png" },
      { name: "Rust Ochre", hex: "#B98A55", image: "assets/colours/earth-tones--rust-ochre.png" },
      { name: "Bulawayo Brown", hex: "#8C5A34", image: "assets/colours/earth-tones--bulawayo-brown.png" },
      { name: "Deep Umber", hex: "#5E3A22", image: "assets/colours/earth-tones--deep-umber.png" },
      { name: "Burnt Sienna", hex: "#A05A34", image: "assets/colours/earth-tones--burnt-sienna.png" },
      { name: "Copper Earth", hex: "#9C6B41", image: "assets/colours/earth-tones--copper-earth.png" },
      { name: "Cocoa", hex: "#4A2F1E", image: "assets/colours/earth-tones--cocoa.png" },
    ],
  },
  {
    id: "reds", name: "Reds",
    swatches: [
      { name: "Blush Wash", hex: "#F3DEDC", image: "assets/colours/reds--blush-wash.png" },
      { name: "Dusty Rose", hex: "#DDA9A5", image: "assets/colours/reds--dusty-rose.png" },
      { name: "Coral Clay", hex: "#C97A6D", image: "assets/colours/reds--coral-clay.png" },
      { name: "Brick Red", hex: "#B14A3A", image: "assets/colours/reds--brick-red.png" },
      { name: "Global Red", hex: "#9E2B25", image: "assets/colours/reds--global-red.png" },
      { name: "Deep Garnet", hex: "#6E1E1E", image: "assets/colours/reds--deep-garnet.png" },
      { name: "Rosewood", hex: "#7A3B37", image: "assets/colours/reds--rosewood.png" },
      { name: "Maroon", hex: "#4E1616", image: "assets/colours/reds--maroon.png" },
    ],
  },
  {
    id: "yellows", name: "Yellows",
    swatches: [
      { name: "Soft Butter", hex: "#F6E9C7", image: "assets/colours/yellows--soft-butter.png" },
      { name: "Warm Vanilla", hex: "#EFD98F", image: "assets/colours/yellows--warm-vanilla.png" },
      { name: "Golden Sand", hex: "#E0B95C", image: "assets/colours/yellows--golden-sand.png" },
      { name: "Sunflower", hex: "#D9A21B", image: "assets/colours/yellows--sunflower.png" },
      { name: "Warm Gold", hex: "#C68A15", image: "assets/colours/yellows--warm-gold.png" },
      { name: "Amber Ochre", hex: "#A8710F", image: "assets/colours/yellows--amber-ochre.png" },
      { name: "Honey Mustard", hex: "#B8860B", image: "assets/colours/yellows--honey-mustard.png" },
      { name: "Dark Mustard", hex: "#7A5A0C", image: "assets/colours/yellows--dark-mustard.png" },
    ],
  },
];

/* Hero slider content — editable from the admin panel. */
let HERO_SLIDES = [
  {
    eyebrow: "Global Paints & Coatings",
    heading: 'Find the <em>colour</em> that feels like home.',
    body: "Reliable paints and coatings for homes, businesses, and projects across Zimbabwe.",
    primaryLabel: "Explore Colour Studio", primaryHref: "colours.html",
    secondaryLabel: "View Projects", secondaryHref: "projects.html",
    image: "assets/projects/project-13.jpg",
  },
  {
    eyebrow: "Made for real projects",
    heading: "<em>Protection</em> that stands up to African conditions.",
    body: "Choose the right coating for walls, roofs, stoeps, wood, metal, and waterproofing.",
    primaryLabel: "Explore Products", primaryHref: "products.html",
    secondaryLabel: "Paint Calculator", secondaryHref: "calculator.html",
    image: "assets/projects/project-08.jpg",
  },
  {
    eyebrow: "Based in Bulawayo",
    heading: "Colour, care, and practical <em>expertise</em>.",
    body: "Talk to Global Paints & Coatings about the right product for your next project.",
    primaryLabel: "Request a Quote", primaryHref: "contact.html",
    secondaryLabel: "Call the team", secondaryHref: "tel:0780281611",
    image: "assets/projects/project-03.jpg",
  },
];

/* Project gallery — safe, non-specific captions only. No client names,
   locations, dates, or product attribution were supplied. */
let PROJECTS = [
  { file: "assets/projects/project-01.jpg", caption: "Residential exterior project — roof and wall work" },
  { file: "assets/projects/project-02.jpg", caption: "Residential exterior project" },
  { file: "assets/projects/project-03.jpg", caption: "Roof and exterior work" },
  { file: "assets/projects/project-04.jpg", caption: "Completed exterior project" },
  { file: "assets/projects/project-05.jpg", caption: "Roof coating detail" },
  { file: "assets/projects/project-06.jpg", caption: "Exterior wall and boundary project" },
  { file: "assets/projects/project-07.jpg", caption: "Boundary wall project" },
  { file: "assets/projects/project-08.jpg", caption: "Residential exterior project" },
  { file: "assets/projects/project-09.jpg", caption: "Exterior detail" },
  { file: "assets/projects/project-10.jpg", caption: "Exterior wall project" },
  { file: "assets/projects/project-11.jpg", caption: "Global Paints project gallery" },
  { file: "assets/projects/project-12.jpg", caption: "Residential exterior project" },
  { file: "assets/projects/project-13.jpg", caption: "Completed project" },
];

function getProductBySlug(slug) {
  return PRODUCTS.find((p) => p.slug === slug) || null;
}

function surfaceLabel(id) {
  const s = SURFACES.find((x) => x.id === id);
  return s ? s.label : id;
}
